config/routes.rb
Rails.application.routes.draw do
  resources :search_opmtimizations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blogs#index'
  resources :blogs do
    # update :purge_image
    resources :comments
    member do
      delete :purge_image
      get :update_image
      # edit :purge_edit_image
    end
  end

  # get 'blogs/image_update', to: 'blogs#image_update'

  resources :users

  resources :categories

  resources :search_optimizations

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true

  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_many :comments, dependent: :destroy
  belongs_to :user

 

  has_one_attached :image

  has_many :search_opmtimizations, dependent: :destroy  

accepts_nested_attributes_for :search_opmtimizations

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

  def index
    # @user ||= current_user
    # @blogs = @user.blogs.all if @user
    @blogs = Blog.all
    authorize @blogs
  end

  def purge_image
    @blog = Blog.find(params[:id])
    @blog.image.purge
    redirect_back fallback_location: root_path, notice: "success(deletion)"
  end

  def update_image
    @blog = Blog.find(params[:id])
    if !@blog.image.present?
      # if @blog.update(blog_params)
      #   flash[:success] = "Blog was successfully updated"
      #   redirect_to blog_path(@blog)
      # else
      #   flash[:danger] = "Something went wrong"
      #   render 'edit'
      # end
    else
      # flash[:danger] = "Image has_one present"
      # redirect_to blog_path(@blog)
      @blog.image.purge
      redirect_to update_image_blog_path(@blog)
    end
  end

  def new
    @blog = Blog.new
    @blog.search_opmtimizations.build
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:success] = "Blog successfully created"
      redirect_to blog_path(@blog)
    else
      flash[:danger] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end


  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      flash[:success] = "Blog was successfully updated"
      redirect_to blog_path(@blog)
    else
      flash[:danger] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      flash[:danger] = 'Blog was successfully deleted.'
      redirect_to blogs_path
    else
      flash[:danger] = 'Something went wrong'
      redirect_to blogs_path, status: :see_other
    end
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :description, :user_id, :image, category_ids: [], search_opmtimizations_attributes: [:keyword, :city])
  end

end

app/views/blogs/_form.html.erb
<%= render 'shared/errors', obj:@blog %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@blog, :html => {class: "form-horizontal", role: "form"}) do |f| %>
             <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :image %>
                </div>
                <div class="col-sm-8" >
                    <%= f.file_field :image, class: "form-control" %>
                </div>
            </div><br/>

            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8" >
                    <%= f.text_field :title, class: "form-control", placeholder:"Title of blog", autofocus: true %>
                </div>
            </div><br/>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of Blog"  %>
                </div>
                <div>
                    <%= f.number_field :user_id, id: :blog_user_id, value: current_user.id, type: :hidden %>
                </div>
            </div><br/>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10", align="right", id="blogs-submit-form-btn" >
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") + cb.text} %>
                    <% end %>
                </div>
            </div>
           
                <%# <%= f.fields_for :search_opmtimizations do |sff| %>
                    <%# <%= render "search_opmtimization_fields", f: sff%>
                <%# <% end %>
                
                <%= link_to_add_fields "Add SEO Info", f, :search_opmtimizations %>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10", align="right", id="blogs-submit-form-btn" >
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            <%= link_to "Back to Blogs", blogs_path %>
        </div>
    </div>
</div>


<%# <script>
    $('form').on('click', 'add_fields', function(event){
        console.log('clicked')
        // var regexp, time;
        // time = new Date().getTime();
        // regexp = new RegExp($(this).data('id'), 'g');
        // $(this).before($(this).data('fields').replace(regexp, time));
        // return event.preventDefault();
    });
</script> %>

app/views/blogs/_search_opmtimization_fields.html.erb
 <div class="form-group row">
    <div class="control-label col-sm-2">
        <%= f.label :keyword %>
    </div>
    <div class="col-sm-8" >
        <%= f.text_field :keyword, class: "form-control" %>
    </div>
</div><br/>
<div class="form-group row">
    <div class="control-label col-sm-2">
        <%= f.label :city %>
    </div>
    <div class="col-sm-8" >
        <%= f.text_field :city, class: "form-control" %>
    </div>
</div><br/>

app/views/blogs/edit.html.erb
<h1 align="center"> Edit this Blog </h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 align="center">Listing all blogs</h1>

<% if !user_signed_in?%>
    <% @blogs.each do |blog| %>

        <div class="row">
            <div class="col-xs-8 col-xs-offset-2", id="blog-details">
                <div class="well well-lg">
                    <div class="blog-title">
                        <%= link_to blog.title, blog_path(blog), :style => 'text-decoration: none;' %>
                    </div>
                    <div class="blog-body">
                        <%= truncate(blog.description, length: 100) %>
                    </div>
                </div> - blog by: 
                <% if blog.user_id != nil %>
                    <%= User.find(blog.user_id).email %>
                <% else %>
                    No author available
                <% end %> 
            </div>
        </div><br/>
    <% end %>
<% else %>
    <div align = center>
        <%= image_tag(current_user.image, class: "w-100 rounded-circle shadow-lg d-block max-auto", style: 'max-width: 10rem;  height: 8rem;') %>
    </div>
    <% @blogs.each do |blog| %>
        <% if blog.user_id != nil %>
            <div class="row">
                <% if current_user.email == User.find(blog.user_id).email %>
                    <div class="col-xs-8 col-xs-offset-2", id="blog-details">
                        <div class="well well-lg">
                            <div class="blog-title">
                                <%= link_to blog.title, blog_path(blog), :style => 'text-decoration: none;' %>
                            </div>
                            <div class="blog-body">
                                <%= truncate(blog.description, length: 100) %>
                            </div>
                            <div class="blog-actions">
                                <%= link_to "Edit this blog", edit_blog_path(blog), class: "btn btn-xs btn-primary" %>
                                <%= link_to "Delete", blog_path(blog), method: :delete, class: "btn btn-xs btn-danger" %>
                            </div>
                        </div> 
                    </div>
                <%end%>
            </div><br/>
        <%end%>
    <% end %>
<%end%>

app/views/blogs/new.html.erb
<h1 align="center"> Create a new Blog </h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h2 align="center">Title: <%= @blog.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
<div class="position-relative">
    <% if @blog.image.present? %>
        <%= image_tag(@blog.image, :class => "blog_image") %>
    <% end %>
    <div class="middle">
        <div class="buttons">
            <%= button_to "Delete Image", purge_image_blog_path(@blog), method: :delete %> |
    
            <%= link_to "Update Image", update_image_blog_path(@blog) %>
        </div>
    </div>
    
</div>
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
        <%= simple_format(@blog.description) %><br/><br/>
        <% @blog.search_opmtimizations.each do |so| %>
        <br/><strong> Search Optimization </strong><br/>
            Category: &nbsp&nbsp<%= so.keyword %><br/>
            City Located: &nbsp&nbsp<%= so.city %>
        <% end %>
        <% if @blog.categories.any? %>
            <p> Categories: <%= render @blog.categories %></p>
        <% end %>
        <h2><%= @blog.comments.count%> comments</h2>
            <%= render @blog.comments %>
            <h3> Add a Comment </h3>
                <%= render 'comments/form' %>
        <% if user_signed_in? %>
        <div class="blog-actions">
            <%= link_to "Edit this blog", edit_blog_path(@blog), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this blog", blog_path(@blog), method: :delete,
            data: { confirm: "Are you sure you want to delete the blog?"},
            class: "btn btn-xs btn-danger" %>
        <% end %>
            <%= link_to "View all blogs", blogs_path, class: "btn btn-xs btn-success" %>
        </div>
</div>

app/views/blogs/update_image.html.erb
Hi updating image here
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@blog, :html => {class: "form-horizontal", role: "form"}) do |f| %>
             <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :image %>
                </div>
                <div class="col-sm-8" >
                    <%= f.file_field :image, class: "form-control" %>
                </div>
            </div><br/>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10", align="right", id="blogs-submit-form-btn" >
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            <%= link_to "Back to Blogs", blogs_path %>
        </div>
    </div>
</div>