config/routes.rb
Rails.application.routes.draw do
  resources :search_opmtimizations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blogs#index'
  resources :blogs do
    # update :purge_image
    resources :comments
    member do
      delete :purge_image
      get :update_image
      # edit :purge_edit_image
    end
  end

  # get 'blogs/image_update', to: 'blogs#image_update'

  resources :users

  resources :categories

  resources :search_optimizations

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/category.rb
class Category < ApplicationRecord

    # validates :name, presence: true, length: {minimum: 3, maximum: 50}

    # validates_uniqueness_of :name

    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 50}
    
    

    has_many :blog_categories
    has_many :blogs, through: :blog_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
          flash[:success] = "Object successfully created"
          redirect_to categories_path
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end
    

    def show
        @category = Category.find(params[:id])
        @category_blogs = @category.blogs.paginate(page: params[:page], per_page: 5)
    end
    
    private

    def category_params
        params.require(:category).permit(:name)
    end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/index.html.erb
<h1 align="center" > Categories here ... </h1>

<div align="center row" >
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <ul class="listing" >
            <div>
                <div class="well col-md-4 col-md-offset-4">
                    <li class="article-title">
                        <%= link_to "#{category.name}", category_path(category) %>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Add a category </h1>

<%= render 'shared/errors', obj:@category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group row">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8" >
            <%= f.text_field :name, class: "form-control", placeholder:"Category", autofocus: true %>
        </div>
    </div><br/>
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10" >
            <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
    <%= link_to "Back to Blogs", categories_path %>
</div>