config/routes.rb
Rails.application.routes.draw do
  resources :search_opmtimizations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blogs#index'
  resources :blogs do
    # update :purge_image
    resources :comments
    member do
      delete :purge_image
      get :update_image
      # edit :purge_edit_image
    end
  end

  # get 'blogs/image_update', to: 'blogs#image_update'

  resources :users

  resources :categories

  resources :search_optimizations

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/models/search_opmtimization.rb
class SearchOpmtimization < ApplicationRecord
  belongs_to :blog
end

app/controllers/search_opmtimizations_controller.rb
class SearchOpmtimizationsController < ApplicationController
  before_action :set_search_opmtimization, only: %i[ show edit update destroy ]

  # GET /search_opmtimizations or /search_opmtimizations.json
  def index
    @search_opmtimizations = SearchOpmtimization.all
  end

  # GET /search_opmtimizations/1 or /search_opmtimizations/1.json
  def show
  end

  # GET /search_opmtimizations/new
  def new
    @search_opmtimization = SearchOpmtimization.new
  end

  # GET /search_opmtimizations/1/edit
  def edit
  end

  # POST /search_opmtimizations or /search_opmtimizations.json
  def create
    @search_opmtimization = SearchOpmtimization.new(search_opmtimization_params)

    respond_to do |format|
      if @search_opmtimization.save
        format.html { redirect_to search_opmtimization_url(@search_opmtimization), notice: "Search opmtimization was successfully created." }
        format.json { render :show, status: :created, location: @search_opmtimization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search_opmtimization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_opmtimizations/1 or /search_opmtimizations/1.json
  def update
    respond_to do |format|
      if @search_opmtimization.update(search_opmtimization_params)
        format.html { redirect_to search_opmtimization_url(@search_opmtimization), notice: "Search opmtimization was successfully updated." }
        format.json { render :show, status: :ok, location: @search_opmtimization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search_opmtimization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_opmtimizations/1 or /search_opmtimizations/1.json
  def destroy
    @search_opmtimization.destroy

    respond_to do |format|
      format.html { redirect_to search_opmtimizations_url, notice: "Search opmtimization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_opmtimization
      @search_opmtimization = SearchOpmtimization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_opmtimization_params
      params.require(:search_opmtimization).permit(:keyword, :city, :blog_id)
    end
end

app/helpers/search_opmtimizations_helper.rb
module SearchOpmtimizationsHelper
end

app/views/search_opmtimizations/_form.html.erb
<%= form_with(model: search_opmtimization) do |form| %>
  <% if search_opmtimization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search_opmtimization.errors.count, "error") %> prohibited this search_opmtimization from being saved:</h2>

      <ul>
        <% search_opmtimization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_field :keyword %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :blog_id, style: "display: block" %>
    <%= form.text_field :blog_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/search_opmtimizations/_search_opmtimization.html.erb
<div id="<%= dom_id search_opmtimization %>">
  <p>
    <strong>Keyword:</strong>
    <%= search_opmtimization.keyword %>
  </p>

  <p>
    <strong>City:</strong>
    <%= search_opmtimization.city %>
  </p>

  <p>
    <strong>Blog:</strong>
    <%= search_opmtimization.blog_id %>
  </p>

</div>

app/views/search_opmtimizations/edit.html.erb
<h1>Editing search opmtimization</h1>

<%= render "form", search_opmtimization: @search_opmtimization %>

<br>

<div>
  <%= link_to "Show this search opmtimization", @search_opmtimization %> |
  <%= link_to "Back to search opmtimizations", search_opmtimizations_path %>
</div>

app/views/search_opmtimizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Search opmtimizations</h1>

<div id="search_opmtimizations">
  <% @search_opmtimizations.each do |search_opmtimization| %>
    <%= render search_opmtimization %>
    <p>
      <%= link_to "Show this search opmtimization", search_opmtimization %>
    </p>
  <% end %>
</div>

<%= link_to "New search opmtimization", new_search_opmtimization_path %>

app/views/search_opmtimizations/new.html.erb
<h1>New search opmtimization</h1>

<%= render "form", search_opmtimization: @search_opmtimization %>

<br>

<div>
  <%= link_to "Back to search opmtimizations", search_opmtimizations_path %>
</div>

app/views/search_opmtimizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @search_opmtimization %>

<div>
  <%= link_to "Edit this search opmtimization", edit_search_opmtimization_path(@search_opmtimization) %> |
  <%= link_to "Back to search opmtimizations", search_opmtimizations_path %>

  <%= button_to "Destroy this search opmtimization", @search_opmtimization, method: :delete %>
</div>