config/routes.rb
Rails.application.routes.draw do
  resources :search_opmtimizations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'blogs#index'
  resources :blogs do
    # update :purge_image
    resources :comments
    member do
      delete :purge_image
      get :update_image
      # edit :purge_edit_image
    end
  end

  # get 'blogs/image_update', to: 'blogs#image_update'

  resources :users

  resources :categories

  resources :search_optimizations

  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <%# <a href="#" class="close" data-dismiss="alert">&#215;×</a> %>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-custom navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">Blog App</a> %>
    <%= link_to "Blog App", blogs_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <a class="nav-link" >
                <%=  button_to "Create Blog", new_blog_path(current_user), method: :get, 
                    :style => 'background: none!important; border: none; padding: 0!important; font-family:
                        sans-serif; color: #0d6efd; cursor: pointer;' %>
            </a>
        </li>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item" >
            <a class="nav-link" >
              <%= button_to "Edit Users", users_path, method: :get, 
                    :style => 'background: none!important; border: none; padding: 0!important; font-family:
                        sans-serif; color: #0d6efd; cursor: pointer;' %>
            </a>
          </li>
        <% end %>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        Hi, <%= current_user.email%>
        <%# <button class="btn btn-outline-success" type="submit">Search</button> %>
      <%# </form> %>
      
      <div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <% if user_signed_in? %>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hi, <%= current_user.email %>, you are a [<%= current_user.role %>]
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" >
                          <%=  button_to "Logout", destroy_user_session_path, method: :delete,
                          :style => 'background: none!important; border: none; padding: 0!important; font-family: arial,
                          sans-serif; color: #0d6efd; cursor: pointer;' %>
                  </a></li>
                  <li><a class="dropdown-item">  
                      <%= button_to "Edit User", edit_user_registration_path(current_user), method: :get,
                          :style => 'background: none!important; border: none; padding: 0!important; font-family: arial,
                          sans-serif; color: #0d6efd; cursor: pointer;' %>
                  </a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item">
                          <%= button_to "Delete my account", registration_path(current_user), method: :delete,
                          :style => 'background: none!important; border: none; padding: 0!important; font-family: arial,
                          sans-serif; color: #0d6efd; cursor: pointer;' %>
                      </a></li>
                </ul>
                <% else %>
                  <a>
                    <%= link_to "SignIn", new_user_session_path %>
                </a>
              <% end %>
            </li>
        </ul>
      </div>
        
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <%# <% if !user_signed_in? %>
      <%# <%= link_to "Login", new_user_session_path %>
    <%# <% end %>

    <% if user_signed_in? %>
      <%# <%= link_to "New Blog", new_blog_path %>
      <%# <%= button_to "Logout", destroy_user_session_path %>
    <% end %>
    <%# <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>